### PR TITLE
Milestone 5 - linking components with the logic

### PR DESCRIPTION
**Pull request by gitnyasha**
- create the handleClick function
- create the onClick event

### CODE REVIEW

**Review by Forison — CHANGES_REQUESTED** [review]
## Status:: Changes Required❌
# 🙋‍♂️ Marshall
#### You have done a good job so far, however, there are a few changes we have to make to get this project approved🙍‍♂️.
#### `App` component 
* [ ] Kindly remove the logic you have in your handleClick method, the logic should be handle in calculate.js.
```
handleClick = (buttonName) => {
  this.setState(calculate(this.state, buttonName));
  }
```
#### OR
```
handleClick = (buttonName) => {
    this.setState(prevState => calculate(prevState, buttonName));
  }
```
* [ ] it passes the total or next value from state to Display   (screenshot)image
- it could be done this way
``` 
<Display result={total} nextKey={next} op={operation} />
```

**[OPTIONAL]**
* [ ] You can use ES6 syntax to avoid bing your methods in a constructor all the time.
* [ ] Stateless components can simply be implemented with functional components.
* [ ] Make sure to add a description to every repo you create on Github.
### That is it kindly make these changes and submit the project for a re-review👨‍🔧.
#### Happy coding👨‍💻 
Addo Forison

**Comment by gitnyasha** [comment]
> ## Status:: Changes Required❌
> # 🙋‍♂️ Marshall
> #### You have done a good job so far, however, there are a few changes we have to make to get this project approved🙍‍♂️.
> #### `App` component
> * [ ]  Kindly remove the logic you have in your handleClick method, the logic should be handle in calculate.js.
> 
> ```
> handleClick = (buttonName) => {
>   this.setState(calculate(this.state, buttonName));
>   }
> ```
> 
> #### OR
> ```
> handleClick = (buttonName) => {
>     this.setState(prevState => calculate(prevState, buttonName));
>   }
> ```
> 
> * [ ]  it passes the total or next value from state to Display   (screenshot)image
> 
> * it could be done this way
> 
> ```
> <Display result={total} nextKey={next} op={operation} />
> ```
> 
> **[OPTIONAL]**
> 
> * [ ]  You can use ES6 syntax to avoid bing your methods in a constructor all the time.
> * [ ]  Stateless components can simply be implemented with functional components.
> * [ ]  Make sure to add a description to every repo you create on Github.
> 
> ### That is it kindly make these changes and submit the project for a re-review👨‍🔧.
> #### Happy coding👨‍💻
> Addo Forison

didn't the instructions say pass the handleClick function to the App component?

**Review by shloch — CHANGES_REQUESTED** [review]
## Hello @gitnyasha , @Forison 

Great job.....works very much smoothly...i love it

calc

### [changes required]

 - please handle the mathematical operation with the button `%`, therefore 2% ==> should give 0.002

- most importantly (real reason for this re-review) is handle DIVISION by ZERO (return `NaN` or `Infinity`)
Screen Shot 2020-07-18 at 7 44 58 AM

**Review by shloch — APPROVED** [review]
## Hello @gitnyasha 

calc

### Good to go

**Pull request merged**
